"""Add GameSession model

Revision ID: 2c572a371247
Revises: 90d0cf6c176d
Create Date: 2024-08-25 14:17:38.341578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c572a371247'
down_revision = '90d0cf6c176d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('number_of_rounds', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_session_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('team_name_key', type_='unique')
        batch_op.create_foreign_key(None, 'game_session', ['game_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('team_name_key', ['name'])
        batch_op.drop_column('game_session_id')

    op.drop_table('game_session')
    # ### end Alembic commands ###
